# Generated by Django 3.0.5 on 2020-04-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('sum', 'Sum'), ('mul', 'Multiplication'), ('sub', 'Subtraction'), ('div', 'Division')], default='sum', max_length=3),
        ),
    ]
